export const SET_USER = 'SET_USER';
export const SET_ERROR = 'SET_ERROR';
export const LOAD_TRANSACTIONS = 'LOAD_TRANSACTIONS';
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
export const TRANSACTION_REMOVE = 'TRANSACTION_REMOVE';
export const TRANSACTION_UPDATE = 'TRANSACTION_UPDATE';

